# Generated by Django 5.0.4 on 2024-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterpieces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterpiece",
            name="language",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="masterpiece",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="masterpiece",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
